#!/usr/bin/env perl

# Parameters supported:
#
# config
# autoconf
#
# Magic markers:
#%# family=auto
#%# capabilities=autoconf

use strict;
use warnings;
use LWP;
use JSON qw/decode_json/;

=head1 NAME

elasticsearch_jvm_memory - A munin plugin that collects JVM memory stats from the JVM of your elasticsearch instances

=head1 APPLICABLE SYSTEMS

Elasticsearch

=head1 CONFIGURATION

None

=head1 BUGS

None known so far. If you find any, let me know.

=head1 AUTHOR

Tomas Doran (t0m) - c<< <bobtfish@bobtfish.net> >>
Kentaro Yoshida - https://github.com/y-ken

=cut

my $host = exists $ENV{'host'} ? $ENV{'host'} : 'localhost';
my $port = exists $ENV{'port'} ? $ENV{'port'} : 9200;
my $proto = exists $ENV{'proto'} ? $ENV{'proto'} : 'http://';
my $user  = exists $ENV{'user'} ? $ENV{'user'} : '';
my $password = exists $ENV{'password'} ? $ENV{'password'} : '';

my $ua = LWP::UserAgent->new;
$ua->timeout(10);

sub get_json_from_url {
  my $uri = shift;
  my $x_user = shift;
  my $x_password = shift;
  my $request = new HTTP::Request('GET', $uri);

  if ($user =~ '' && $password =~ '') {
    $request->authorization_basic($user, $password);
  }

  my $res = $ua->request($request);
  Carp::confess($res->code . " for " . $uri) unless $res->is_success;
  my $data = do { local $@; eval { decode_json($res->content) } };
  die("Could not decode JSON from: " . $res->content) unless $data;
  return $data;
}

my $data = get_json_from_url("$proto$host:$port/_nodes/_local/stats/jvm");
my %out = (heap_max => 0, heap_committed => 0, heap_used => 0, non_heap_committed => 0, non_heap_used => 0);

foreach my $full_node_name (keys %{$data->{nodes}}) {
    next unless $data->{nodes}{$full_node_name};
    foreach my $name (grep { /_in_bytes$/ } keys %{ $data->{nodes}{$full_node_name}{jvm}{mem} }) {
        my ($dname) = $name =~ m/(.+)_in_bytes$/;
        $out{$dname} += $data->{nodes}{$full_node_name}{jvm}{mem}{$name};
    }
}
if ($ARGV[0] and $ARGV[0] eq 'config') {
    print "graph_args --base 1024\n";
    print "graph_title Elasticsearch JVM memory usage\n";
    print "graph_category elasticsearch\n";
    print "graph_vlabel Bytes\n";
    print "graph_order heap_max heap_committed heap_used non_heap_committed non_heap_used\n";

    foreach my $name (keys %out) {
        print "$name.label $name\n"."$name.type GAUGE\n";
    }
}
elsif (!$ARGV[0] || $ARGV[0] eq 'autoconf') {
    foreach my $name (keys %out) {
        print "$name.value " . $out{$name} . "\n";
    }
}

exit(0);
